// zm_stellar_facility.res
// zm_stellar_facility by sW1ngFly.

maps/zm_stellar_facility.bsp
maps/zm_stellar_facility.res
gfx/env/m_bas_bk.tga
gfx/env/m_bas_dn.tga
gfx/env/m_bas_ft.tga
gfx/env/m_bas_lf.tga
gfx/env/m_bas_rt.tga
gfx/env/m_bas_up.tga
models/sW1ngFly/zm_stellar_facility/jb_hanging_Spacesuit.mdl
models/sW1ngFly/zm_stellar_facility/ut2k4_HoverBikeAS.mdl
sound/sW1ngFly/zm_stellar_facility/alien_purrmachine.wav
sound/sW1ngFly/zm_stellar_facility/distant_ambience.wav
sound/sW1ngFly/zm_stellar_facility/engine1.wav
sound/sW1ngFly/zm_stellar_facility/engine2.wav
sound/sW1ngFly/zm_stellar_facility/engine3.wav
sound/sW1ngFly/zm_stellar_facility/fluorescent_hum.wav
sound/sW1ngFly/zm_stellar_facility/inside_drone.wav
sound/sW1ngFly/zm_stellar_facility/whining_ambience.wav
sound/sW1ngFly/zm_stellar_facility/wind_tunnel1_noloop.wav
sound/sW1ngFly/zm_stellar_facility/windtunnel.wav
sprites/sW1ngFly/zm_stellar_facility/glow.spr