
chateau.wad
cs_assault.wad
cs_havana.wad
de_storm.wad
de_vertigo.wad
halflife.wad
nighrise.wad
gfx/env/tsccity_up.tga
gfx/env/tsccity_dn.tga
gfx/env/tsccity_lf.tga
gfx/env/tsccity_rt.tga
gfx/env/tsccity_ft.tga
gfx/env/tsccity_bk.tga
models/zm_highrise2/sink.mdl
models/zm_highrise2/leafs1.mdl
models/couch_leather-black.mdl
models/buzzer_gorshok.mdl
models/zm_highrise2/chair_office.mdl
models/zm_highrise2/couch_leather-black.mdl
models/ez-mebel_k_verhu_zhopou.mdl
sprites/glow02.spr
models/zm_highrise2/ez_trup1.mdl
models/zm_highrise2/ez_trup2.mdl
models/zm_highrise2/ez_trup3.mdl
models/zm_highrise2/ez_trup4.mdl
models/zm_highrise2/ez_trup5.mdl
models/zm_highrise2/ez_trup6.mdl
models/zm_highrise2/ez_trup7.mdl
models/zm_highrise2/ez_trup8.mdl
models/zm_highrise2/ez_trup9.mdl
sound/misc/plane_drone.wav
sound/player/pl_duct2.wav
sound/player/pl_duct3.wav
maps/zm_zombie_office.txt